<?php
$customerEmail=Mage::getSingleton('core/session')->getAddWishEmail($email);
if(isset($customerEmail)){
?>
<meta content="<?php echo $customerEmail;?>" name="aw:userEmail"/>
<?php
}else{
if(Mage::getSingleton('customer/session')->isLoggedIn()){
$customer=Mage::getSingleton('customer/session')->getCustomer();
?>
<meta content="<?php echo $customer->getEmail();?>" name="aw:userEmail"/>
<?php
}
}
?>