<?php $quote = Mage::getSingleton('checkout/session')->getQuote(); ?><span class="addwish-basket" style="display:none"
	data-total="<?php echo number_format($quote->getData('grand_total'), 2, '.', '');?>">
<?php 
$cartItems = Mage::getModel('checkout/cart')->getItems();
if(count($cartItems)>0){
	foreach($cartItems->getData() as $cartProduct){
		$product=Mage::getModel('catalog/product')->load($cartProduct['product_id']);
		if($product->isVisibleInSiteVisibility()){ ?>
	<span class="addwish-product"
		data-url="<?php echo $product->getProductUrl();?>"
		data-id="<?php echo $product->getId();?>"
		data-productnumber="<?php echo $product->getSku();?>"
		data-quantity="<?php echo (int)$cartProduct['qty'];?>">
	</span><?php
		}
	}
}
?>
</span>