<?php
$quote = Mage::getSingleton('checkout/session')->getQuote();
?><span class="addwish-basket" style="display:none"
data-total="<?php echo number_format($quote->getData('subtotal'), 2, '.', '');?>"
data-tax="<?php echo number_format($quote->getData('grand_total')-$quote->getData('subtotal'), 2, '.', '');?>"
data-noshipping="">
<?php
$cartItems = Mage::getModel('checkout/cart')->getItems();
if(count($cartItems)>0){
foreach($cartItems->getData() as $cartProduct){
	$product=Mage::getModel('catalog/product')->load($cartProduct['product_id']);
if($product->isVisibleInSiteVisibility()){
	?>
	<span class="addwish-product"
data-unit-price="<?php echo number_format(Mage::getModel('directory/currency')->formatTxt($cartProduct['price'], array('display' => Zend_Currency::NO_SYMBOL)), 2, '.', '');?>"
data-url="<?php echo $product->getProductUrl();?>"
data-productnumber="<?php echo $product->getId();?>"
data-sku="<?php echo $product->getSku();?>"
data-quantity="<?php echo (int)$cartProduct['qty'];?>"
data-unit-tax="<?php echo number_format($cartProduct['tax_amount'], 2, '.', '');?>">
</span>
	<?php
}
}
}
?>

</span>