<?php 
	$cart = Mage::getSingleton('checkout/cart');
	$quote = $cart->getQuote();
	$cartItems = $cart->getItems();
?>
<span class="addwish-basket addwish-cart" style="display:none"
	data-total="<?php echo number_format($quote->getData('grand_total'), 2, '.', '');?>">
<?php foreach($cartItems as $cartProduct):
	$product=Mage::getModel('catalog/product')->load($cartProduct['product_id']);
	if($product->isVisibleInSiteVisibility()): ?>
	<span class="addwish-product"
		data-url="<?php echo $product->getProductUrl();?>"
		data-id="<?php echo $product->getId();?>"
		data-productnumber="<?php echo $product->getSku();?>"
		data-quantity="<?php echo (int)$cartProduct['qty'];?>">
	</span>
	<?php endif ?>
<?php endforeach ?>
</span>