<?php
$orderIds = $this->getOrderIds();
if($orderIds && count($orderIds)) {
	$orderId = $orderIds[0];
	$order = Mage::getModel('sales/order')->load($orderId);
	if($order && $order->getId()):?>
		<span class="addwish-conversion" style="display:none;"
			data-ordernumber="<?php echo $order->getIncrementId();?>"
			data-total="<?php echo number_format($order->getGrandTotal(), 2, '.', '');?>">
		<?php $cartItems= $order->getAllItems();
		foreach($cartItems as $cartProduct):
		$product=Mage::getModel('catalog/product')->load($cartProduct->getData('product_id'));
			if($product->isVisibleInSiteVisibility()):?>
				<span class="addwish-product"
					data-url="<?php echo $product->getProductUrl();?>"
					data-id="<?php echo $product->getId();?>"
					data-productnumber="<?php echo $product->getSku();?>"
					data-quantity="<?php echo (int)$cartProduct->getData('qty_ordered');?>">
				</span>
			<?php endif; ?>
		<?php endforeach; ?>
		</span>
	<?php endif;
}