<?php 
$model = Mage::getModel('awext/awext')->load(Mage::app()->getStore()->getStoreId());
if($model->getData('userId')!=''){
?><script type="text/javascript">
(function() {
var aws = document.createElement('script');
aws.type = 'text/javascript';
if (typeof(aws.async) != "undefined") { aws.async = true; }
aws.src = (window.location.protocol == 'https:' ? 'https://d1pna5l3xsntoj.cloudfront.net' :
'http://cdn.addwish.com') + '/scripts/company/awAddGift.js#<?php echo $model->getData('userId');?>';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(aws, s);
})();
</script>
<span id="addwish-data" data-formkey="<?php echo Mage::getSingleton('core/session')->getFormKey();?>" style="display:none"></span>
<?php
}
?>