<?php
$product = Mage::registry('current_product');
$productData = Mage::helper('awext')->getProductData($product);

$parts=explode("uenc/", Mage::helper('checkout/cart')->getAddUrl($product));
$parts=explode("/product",$parts[1]);
$productData['uenc'] = $parts[0];
$productData['formkey'] = Mage::getSingleton('core/session')->getFormKey();
?>
<span class="addwish-product-info" style="display:none"
<?php foreach($productData as $key => $value):
	if(is_bool($value)) {
		$value = $value ? "true" : "false";
	} else if(is_array($value)) {
		$value = json_encode($value);
	}
?>
	data-<?php echo strtolower($key)?>="<?php echo htmlspecialchars($value)?>"
<?php endforeach ?>
></span>