<div class="headertext">&nbsp;</div>
<div class="entry-edit" style="top:-200px">
	<div class="entry-edit-head">
		<h4>Recommendations</h4>
	</div>
	<form action="" method="post">
<?php
$currentStore= Mage::app()->getDefaultStoreView()->getStoreId();
if(Mage::app()->getRequest()->getParam('storeconfig')){
$currentStore=Mage::app()->getRequest()->getParam('storeconfig');
}
?>
	<input type="hidden" name="action" value="recomendations">
		<input name="form_key" type="hidden"
			value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<fieldset class="config" id="general_recommend">
			<legend>Recomendations</legend>
			<?php 
			$model = Mage::getModel('awext/awext')->load($currentStore);
			?>
				<div style="margin-bottom: 20px;" class="introtext">
              Personalised recommendations will be displaying unique, relevant content targeted to their needs and shopping habits.
              All the hard work of getting setup is being done by the addwish team, so please if you havn't done so yet, reach out to us, and we will make sure that all your requirements will be handled quickly.
              <br>Get setup with personalised recommendations:
              <br>
              <ul style="list-style: none none none; margin-left: 20px;">
                <li>Encourage your users to continue shopping on your shop</li>
                <li>Customised algorithms to suit your customer experience strategy</li>
                <li>Use them everywhere you wish, both on your front page, product page, category pages or any where else you find it relevant</li>
              </ul>

Our recommendations feature automatically analyses user behaviour to recommend products that customers are most likely to buy. 
<br>
              <br>
In this Magento extension we have included the possibility of having a special upsell page. The upsell page will be shown everytime a product is added to the cart.<br>
              On this upsell page we will have the opotunity to show specialised product recommendations for upsell based on the user and on the contents of the cart.
              <br>
              You can enable and disable the upsell page below. <br><br><b>Before enabling the upsell page, <u>please contact addwish support on <a href="mailto:support@addwish.com">support@addwish.com</a></u> to get you requirements for the recommendations on the upsell page implemented <br> Also please visit the upsell page before enabling the page to tailor the design of the upsell page. You can visit the page from this link : <br>
              <a href="<?php echo Mage::getBaseUrl();?>awext/index/upsells?productId=3" target="_blank">awext/index/upsells?productId=3</a></b><br><i>Notice that you can change the ID in the url, to see how the product recommendations will depend on the product added to the cart.
              </i>
</div>
              <div style="clear:both"></div>
              <div style="float: left">Enable upsell page</div>
              <input type="checkbox" style="margin-left: 10px;"  <?php if($model->getData('enableUpsells')==1){echo "checked='checked'";} ?> value="1" name="addwishUpsells">
              
              
              <div style="clear:both; margin-top: 10px;"></div>
              <hr>
              
              <div style="float: left; margin-top: 10px;"><input type="submit" class="form-button" value="Update Settings" name="submit"></div>
              
              
              <div style="clear:both"></div>
              
			
		</fieldset>
	</form>
</div>