<style type="text/css">
table.addwishgrid { 
    width: 100%; 
    border-collapse: collapse; 
   /*  margin:50px auto; */
    }
/* Zebra striping */
table.addwishgrid tr:nth-of-type(odd) { 
    background: #eee; 
    }
table.addwishgrid th { 
    background: #6f8992; 
    color: white; 
    font-weight: bold; 
    }
table.addwishgrid td,table.addwishgrid th { 
    padding: 6px;
    border: 1px solid #ccc;
    text-align: left;
    font-size: 13px;
    }
</style>
<form action='' method='post'>
<input type='hidden' name='action' value='updateattributes'/>
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<div style="float: right; margin-right: 20px;">
	<input type="submit" class="form-button" value="Save" name="submit">
</div>
<table class="addwishgrid">
    <thead>
        <tr>
            <th>Attribute Name</th>
            <th>Attribute Code</th>
            <th>Attribute Type</th>
            <th>Include ?</th>
        </tr>
    </thead>
    <tbody>
<?php
$productAttrs = Mage::getResourceModel('catalog/product_attribute_collection');
$model = Mage::getModel('awext/awext')->load(1);
$selected_attributes=explode(",",$model->enabled_attributes);
foreach ($productAttrs as $productAttr) { 
/** @var Mage_Catalog_Model_Resource_Eav_Attribute $productAttr */
	if($productAttr->getData('is_filterable')==1){
		if(in_array($productAttr->getAttributeCode(),$selected_attributes)){
			$checked='checked="checked"';		
		}else{
			$checked='';
		}
		echo "<tr><td>".$productAttr->getFrontendLabel()."</td><td>".$productAttr->getAttributeCode()."</td><td>".$productAttr->getFrontendInput()."</td><td><input type='checkbox' name='includein[]' value='".$productAttr->getAttributeCode()."' ".$checked."></td></tr>";
	}
}
?>
    </tbody>
</table>
</form>